Messages:
  ChallengeTitle: "&c&lYour Challenge is"
  RandomList: "&e%RandomList%"
  ChallengeToServer: "&c%Player% &eHas died and needs to do the %RandomList% Challenge!"

ChallengeList:
  - "#1 Parkour challenge"
  - "#2 No Food for 20 minutes"
  - "#3 Eat 1 hot Gummy bear"
  - "#4 Screenshare for 20 minutes"
  - "#5 Blindness for 20 minutes"
  - "#6 Wooden tools for 1 hour"
  - "#7 Mine for 30 minutes and donate all resources to everyone evenly"
  - "#8 Play on 30FOV for 30 minutes"
  - "#9 Slay all your animals"
  - "#10 Your shops are now 80% off for 20 minutes"
  - "#11 Don't pick up your items"
  - "#12 Donate half your diamonds to everyone"
  - "#13 Text your crush that you like them"
  - "#14 Allow a random player to make a post on any of your social media accounts"
  - "#15 Toggle sneak for 30 minutes"
  - "#16 Play in third person for 30 minutes"
  - "#17 Let a random player pick 1 chest in your base to give away"
  - "#18 Get yourself banned from a discord server you're in"
  - "#19 Put ice in your pants and play"
  - "#20 Eat shitty beans"
  - "#21 Drink Challenge"
  - "#22 Max DPI/Lowest DPI"
  - "#23 Fill your mouth with marshmallows and keep them in there for 10 minutes"
  - "#24 Post your last picture into #General"
  - "#25 Eat tooth paste and drink a glass of orange juice right after"
  - "#26 You have to watch as everyone leaves their mark on your base for 10 minutes"
  - "#27 Add Curse of vanishing to Random Tool/Armor"
  - "#28 Disenchant a random item"
  - "#29 Pay double on your next purchase"